version: '3.4'

services:
  metabase:
    image: metabase/metabase:${METABASE_VERSION}
    networks:
      - default
      - web
      - monitoring
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ${METABASE_STORAGE}:/metabase-data
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=3000
        - traefik.docker.network=web
        - traefik.frontend.passHostHeader=true
        - traefik.frontend.redirect.entryPoint=${DOMAIN_ENTRYPOINT}
        - traefik.frontend.rule=Host:${METABASE_DOMAIN}
        - traefik.backend.loadbalancer.swarm=true
        - traefik.backend.loadbalancer.stickiness=false
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1m
        failure_action: rollback
        order: start-first
        parallelism: 1

networks:
  web:
    external: true
  monitoring:
    external: true
