version: '3.4'

services:
  backup-restore:
    image: schickling/postgres-restore-s3
    networks:
      - default
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - S3_ACCESS_KEY_ID=${AWS_S3_KEY}
      - S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET}
      - S3_BUCKET=${AWS_S3_BUCKET}
      - S3_PREFIX=${AWS_S3_PREFIX}
      - S3_REGION=${AWS_S3_REGION}
      - DROP_PUBLIC=yes
    deploy:
      mode: global
